### ISSUE TITLE
Is the cryptojs dependency needed?

### ISSUE THREAD

**Issue by joerg1985** [alexneo2003/playwright-azure-reporter#12]
There is a cryptojs dependency which seems to be unused and seems to be not maintained anymore.
The last push to their repo was 11 years ago, i don't think there is any support for this.

Background is, i am currently checking if we will use this plugin in our pipeline and i have to ensure all the components are maintained and have a valid license.

**Comment by alexneo2003** [comment]
it's my bad
i think it was lost after some refactoring
