### ISSUE TITLE
Unable to configure @alex_neo/playwright-azure-reporter

### ISSUE THREAD

**Issue by rovmak** [alexneo2003/playwright-azure-reporter#15]
This is the error that i get and i cannot figure it out.

Failed to create test run. Reporting is disabled.
undefined:1
Cannot read properties of null (reading 'value')
^

SyntaxError: Unexpected token 'C', "Cannot rea"... is not valid JSON
at JSON.parse ()
at AzureDevOpsReporter.onBegin

**Comment by alexneo2003** [comment]
Show you reporter config, please

**Comment by rovmak** [comment]
reporter: [
    ['list'],
    [
      './src/playwright-azure-reporter.ts',
      {
        orgUrl: azureConfig.orgUrl,
        token: azureConfig.token,
        planId: azureConfig.testPlanId,
        projectName: azureConfig.projectName,
        environment: 'QA',
        testRunTitle: 'Playwright Test Run',
        logging: false,
        isDisabled: false,
        uploadAttachments: true,
        attachmentsType: ['screenshot', 'trace'],
      } as AzureReporterOptions,
    ],
  ],

**Comment by alexneo2003** [comment]
@rovmak are you sure you using right installed reporter from package?)

**Comment by rovmak** [comment]
I used this command to install: npm install @alex_neo/playwright-azure-reporter

**Comment by alexneo2003** [comment]
> I used this command to install: npm install @alex_neo/playwright-azure-reporter

I ask you to show me your config. You show me this `'./src/playwright-azure-reporter.ts'` 
😐😐😐

**Comment by alexneo2003** [comment]
> I copied it as it is from your code and pasted it in my project

Read [usage](https://github.com/alexneo2003/playwright-azure-reporter#usage) section, especially about `playwright.config.ts`

**Comment by alexneo2003** [comment]
> I did. And everything is exactly as it says. I am sorry. But i am sure i am doing something wrong. Just tried everything.

You coping [this](https://github.com/alexneo2003/playwright-azure-reporter/issues/15#issuecomment-1424519873) config from package source code - you no need to do that!!
You need to copy reporter config code from README and change value like token with you own!

**Comment by rovmak** [comment]
It worked! I found my mistake. Thank you for your help! Much appreciate it. I am fairly new to all this so still learning (:

**Comment by vinda-parab** [comment]
@rovmak i am facing the same issue, though I am referring the package, issue persists. Can you pls let me know, what have you fixed?

**Comment by vinda-parab** [comment]
@alexneo2003  as per readme file, there is an import from /src path.

_import { AzureReporterOptions } from './src/playwright-azure-reporter';_

Should we copy the src folder from package to our codebase?

**Comment by alexneo2003** [comment]
> @alexneo2003 as per readme file, there is an import from /src path.
> 
> _import { AzureReporterOptions } from './src/playwright-azure-reporter';_
> 
> Should we copy the src folder from package to our codebase?
> 

i'm fixing this moment in readme
```ts
import { AzureReporterOptions } from '@alex_neo/playwright-azure-reporter/dist/playwright-azure-reporter';
```

**Comment by vinda-parab** [comment]
@alexneo2003 Thank you for looking into this. I made this change, but the error is not still resolved. please find screenshots attached in above comments.

**Comment by alexneo2003** [comment]
> @alexneo2003 Thank you for looking into this. I made this change, but the error is not still resolved. please find screenshots attached in above comments.

are you sure you using correct `orgUrl`?
i think what `azuredevops` is probably mistake
correct url looks like `https://dev.azure.com/`
look at the browser url field, when you working with Azure DevOps, and check pls

**Comment by vinda-parab** [comment]
@alexneo2003 the path in the error is pointing to "/src" even after changing the path to dist in import.

_azure: Failed to create test run. Reporting is disabled.
undefined:1
unable to verify the first certificate
^

SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at AzureDevOpsReporter.onBegin (D:\PW\Playwright_Project\Playwright_Project\node_modules\@alex_neo\playwright-azure-reporter\src\playwright-azure-reporter.ts:250:34)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)_

the devops server url is copied as it is from browser.


<img width="209" alt="image" src="https://user-images.githubusercontent.com/67003742/220557446-ced135c3-dfb9-4fc2-ae5a-981e2eef55b6.png">

**Comment by alexneo2003** [comment]
> <img alt="image" width="209" src="https://user-images.githubusercontent.com/67003742/220557446-ced135c3-dfb9-4fc2-ae5a-981e2eef55b6.png">
> 
> Also note, the project is under the Azure Collection. So the complete url till the prj is: https://azuredevops.persistent.co.in/Collection_Name/PrjName Please suggest.

sorry, but i don't know anything about you "azure collection" and what is it.
but main Azure Test Cases management system what you should using for using this reporter is **Azure DevOps** what linked at - https://dev.azure.com/

**Comment by vinda-parab** [comment]
@alexneo2003 the url I have used is of Azure DevOps Server.
Does it means - this reporter is for Azure DevOps **Services** and not Azure DevOps **Server**?

**Comment by alexneo2003** [comment]
> @alexneo2003 the url I have used is of Azure DevOps Server. Does it means - this reporter is for Azure DevOps **Services** and not Azure DevOps **Server**?

this reporter used [this](https://github.com/microsoft/azure-devops-node-api) package as main api package for Azure DevOps. pls, read doc's about it
