### ISSUE TITLE
[Feature]: Dynamic testRunConfig

### ISSUE THREAD

**Issue by joerg1985** [alexneo2003/playwright-azure-reporter#16]
We are currently running different browsers sequentially in different stages to inject the correct `configurationIds` to the `testRunConfig`. So the TestRun in the Azure UI is mapped to the correct configuration.

In the future we would like to run the tests in one stage to with multiple workers to reduce the runtime of the tests.
This will allow us to implement a locking mechanism to ensure the tests with different browsers will not disturb each other.

To make this working we need the option to set multiple `configurationIds` inside the `testRunConfig` or a way to create the `testRunConfig` dynamically. To create the `testRunConfig` dynamically would be a small change in the plugin, enabling alot of other usecases too.

One way to achieve this would be to have a `testRunConfigCallback` inside the plugin configuration.
The callback could be called in `_createRun` with one argument, the `TestCase` and use the `TestCase.parent().project()` to decide which `testRunConfig` to return.

**Comment by alexneo2003** [comment]
1. i'm not using `configurationIds` in my projects and have no expertise with him
2. if looking at ADO [doc](https://learn.microsoft.com/en-us/rest/api/azure/devops/test/runs/create?view=azure-devops-rest-7.0&tabs=HTTP) we can find 
> configurationIds | integer[] | IDs of the test configurations associated with the run.

  I assume that you can pass several configurationIds and it should be attached to testRun, i think so, but i can't to check this

3. one tests running === one test run at ADO. as alternative for running your tests i think you can write something like this
you need [npm-run-all](https://github.com/mysticatea/npm-run-all/blob/master/docs/run-s.md) package
and next running scripts
```json
  "scripts": {
    "test:chromium": "npx playwright test --project=chromium",
    "test:firefox": "npx playwright test --project=firefox",
    "test:webkit": "npx playwright test --project=webkit",
    "test:all": "run-s -c test:chromium test:firefox test:webkit"
  },
```
the main thing - pass `-c` flag in run-s it will allow run next test project when last was failed
as result you receive: parallelism within each project, all of you projects will be running separately, ADO testRun for each project

<img width="450" alt="Monosnap example spec ts — pw-example 2023-02-17 16-35-49" src="https://user-images.githubusercontent.com/11705902/219683891-3fee7926-321f-41fa-9aa7-b828c0619346.png">

**Comment by joerg1985** [comment]
> 1. i'm not using `configurationIds` in my projects and have no expertise with him
> 2. if looking at ADO [doc](https://learn.microsoft.com/en-us/rest/api/azure/devops/test/runs/create?view=azure-devops-rest-7.0&tabs=HTTP) we can find
> 
> > configurationIds | integer[] | IDs of the test configurations associated with the run.
> 
> I assume that you can pass several configurationIds and it should be attached to testRun, i think so, but i can't to check this

Yes, it is possible to use multiple `configurationIds`, but the testcase run will be linked in the UI only one `configurationID`.
(I am not sure about the logic, looks like the lowest ID is set, the order is ignored)

I don't know why there is an array in the API, but thats the observed behaviour of the UI.

> 3. one tests running === one test run at ADO. as alternative for running your tests i think you can write something like this
>    you need [npm-run-all](https://github.com/mysticatea/npm-run-all/blob/master/docs/run-s.md) package
>    and next running scripts
> 
> ```json
>   "scripts": {
>     "test:chromium": "npx playwright test --project=chromium",
>     "test:firefox": "npx playwright test --project=firefox",
>     "test:webkit": "npx playwright test --project=webkit",
>     "test:all": "run-s -c test:chromium test:firefox test:webkit"
>   },
> ```
> 
> the main thing - pass `-c` flag in run-s it will allow run next test project when last was failed as result you receive: parallelism within each project, all of you projects will be running separately, ADO testRun for each project
> 
> <img alt="Monosnap example spec ts — pw-example 2023-02-17 16-35-49" width="450" src="https://user-images.githubusercontent.com/11705902/219683891-3fee7926-321f-41fa-9aa7-b828c0619346.png">

However we achieve the parallelism or even run sequentially, there is the need to set the corresponding `configurationIds` for each run to get it mapped in the UI. So there is some logic required to control the configurationIds and a callback for the whole `testRunConfig` would be a flexible way for this.

**Comment by alexneo2003** [comment]
> Yes, it is possible to use multiple `configurationIds`, but the testcase run will be linked in the UI only one `configurationID`. (I am not sure about the logic, looks like the lowest ID is set, the order is ignored)
> 
> I don't know why there is an array in the API, but thats the observed behaviour of the UI.
> 
Oh, yes. ADO api has some stranger things)
> However we achieve the parallelism or even run sequentially, there is the need to set the corresponding `configurationIds` for each run to get it mapped in the UI. So there is some logic required to control the configurationIds and a callback for the whole `testRunConfig` would be a flexible way for this.
you can use some environment variable to pass it into config
like 
```json
"scripts": {
  "test:chromium": "cross-env CONFIG_ID=15 npx playwright test --project=webkit"
}
```
`playwrignt.config.ts`
```diff
reporter: [
    ['list'],
    [
      '@alex_neo/playwright-azure-reporter',
      {
        orgUrl: 'https://dev.azure.com/your-organization-name',
        token: 'AZURE-TOKEN',
        planId: 44,
        projectName: 'SampleSample',
        environment: 'AQA',
        logging: true,
        testRunTitle: 'Playwright Test Run',
        publishTestResultsMode: 'testRun',
        uploadAttachments: true,
        attachmentsType: ['screenshot', 'video', 'trace'],
        testRunConfig: {
          owner: {
            displayName: 'Alex Neo',
          },
          comment: 'Playwright Test Run',
+         configurationIds: [process.env.CONFIG_ID || 1]
        },
      } as AzureReporterOptions,
    ],
  ],
```

**Comment by joerg1985** [comment]
We are currently using the environment variable way: `configurationIds: [Number(process.env.CONFIG_ID)],`.
But this will block an local locking mechanism, to ensure some tests are not running concurrently.
Which was the reason to raise this ticket, to have dynamic way to set this.

Some more background to the locking mechanism, we need this to ensure some external interfaces with a limited working set of data are not called concurrently. Or later one when we integrate some hardware into the process to ensure the hardware is not used concurrently.
If we could use workers for concurency, we could just use a lock file (or whatever) to implement a local lock on the system.
As soon as we start to use different stages, etc. we are runnig on different VMs and need a external locking mechanism.

**Comment by joerg1985** [comment]
I gave it a try, see this [branch](https://github.com/joerg1985/playwright-azure-reporter/tree/callback).

The Suite is passed to the Callback, it should be possible to get the project configuration from there. 
I am not sure about saving the Suite in the instance, this might make some problems (in mode == testRun).

And all changes are currently not tested at all ...

**Comment by joerg1985** [comment]
I had a closer look now and it looks my change is not usefull in our case.
We need a custom _getTestPointIdsByTCIds implementation to pick the correct test point of this test run.

**Comment by alexneo2003** [comment]
i'm appreciate for you work but i can't check this because i haven't opportunities. we don't using such scenarios.
if you can and if you have expertise in this area you can create PR with this features.
but you must be sure that it works as it should.
i will publish you PR as beta package for testing.
you are welcome

**Comment by joerg1985** [comment]
@alexneo2003 thanks for the offer to create a beta later on, i do not expect you to active check this or work on this.
The main reason for me to write updates here is to keep you / others updated there is still progress in this feature request.

**Comment by joerg1985** [comment]
@alexneo2003 i created the PR #18 with the change. 

If there are any questions to the change, just add comments to it and i will try to answert them.

**Comment by alexneo2003** [comment]
> @alexneo2003 i created the PR #18 with the change.
> 
> If there are any questions to the change, just add comments to it and i will try to answert them.

yes, i'm seen it.
i'm realy appreciate for you work.
I have a heavy workload at work and have no time to review you PR, i will try to do it soon
