### ISSUE TITLE
Feature switch to publish test results in ADO

### ISSUE THREAD

**Issue by amitasil** [alexneo2003/playwright-azure-reporter#19]
Hi @alexneo2003,

Can we have a feature switch ON/OFF in playwright to enable/disable (with the enabled option as default) the reporting of test runs in Azure DevOps?

Something like:

**enableAzureReporter: 'Yes'**

`[
      '@alex_neo/playwright-azure-reporter',
      {
        enableAzureReporter: 'Yes',
        orgUrl: 'https://dev.azure.com/your-organization-name',
        token: 'AZURE-TOKEN',
        planId: 44,
        projectName: 'SampleSample',
        environment: 'AQA',
        logging: true,
        testRunTitle: 'Playwright Test Run',
        publishTestResultsMode: 'testRun',
        uploadAttachments: true,
        attachmentsType: ['screenshot', 'video', 'trace'],
        testRunConfig: {
          owner: {
            displayName: 'Alex Neo',
          },
          comment: 'Playwright Test Run',
        },
      } as AzureReporterOptions,
    ]`

Thanks!

**Comment by alexneo2003** [comment]
isDisabled [true/false] - Disable reporter. Default: false.
