### ISSUE TITLE
How to handle iterations in test results?

### ISSUE THREAD

**Issue by amitasil** [alexneo2003/playwright-azure-reporter#20]
Hi @alexneo2003 ,

Some of my tests in ADO are having dynamic parameters and I need to run them in iterations based on the number of records in the parameters table.
How can I handle such a situation with your implementation?

https://learn.microsoft.com/en-us/rest/api/azure/devops/test/iterations/get?view=azure-devops-rest-7.1&tabs=HTTP

Thanks!

**Comment by alexneo2003** [comment]
As you see ADO [api](https://learn.microsoft.com/en-us/rest/api/azure/devops/test/iterations?view=azure-devops-rest-7.1) does not have methods for post iterations data.
I think this is beyond the capabilities of this package and ADO api to.
