### ISSUE TITLE
[Feature]: Change planId to accept string

### ISSUE THREAD

**Issue by mparsons007** [alexneo2003/playwright-azure-reporter#24]
We have test cases that use different data and likewise are hosted in separate Test Plans in ADO.

Suggesting the planId be changed to accept a string, then convert to a number within the code where necessary.

This would allow for the use of environment variables in the pipeline to control which test plan gets updated.

**Comment by alexneo2003** [comment]
@mparsons007 if you will convert you environment from string to int like 
```ts
planId: parseInt(process.env.PLAN_ID, 10)
```
will this solve your problem?

**Comment by mparsons007** [comment]
@alexneo2003 Thank you, that worked!

I made one small adjustment and added ! to process.env.PLAN_ID so VS Code wouldn't complain. 

`planId: parseInt(process.env.PLAN_ID!, 10),`
