### ISSUE TITLE
Error while publishing test results 

### ISSUE THREAD

**Issue by ravindrakumar6** [alexneo2003/playwright-azure-reporter#29]
@alexneo2003 

getting this error 
![image](https://user-images.githubusercontent.com/104666900/233263969-a957572b-507a-450b-9c5a-e45b9ade8f74.png)

my TFS test case status is as below
![image](https://user-images.githubusercontent.com/104666900/233264007-1527dfd0-3d74-4880-b1e5-96c3648e8775.png)

could you please help me with what could be wrong

**Comment by ravindrakumar6** [comment]
![image](https://user-images.githubusercontent.com/104666900/233290493-5e96e2db-9b4d-4ebd-aada-47f45d2a296a.png)

these are Automaiton Statuses available

**Comment by ravindrakumar6** [comment]
@alexneo2003 , hey alex i was going through all the urls from specsync , and this sentence in your documentation "You must register an ID already existing test cases from Azure DevOps before running tests." means something , i need to link test cases which are written in typescript playwright framework first i need to associate with AzureDevOps test case workitems ? and then only i can use ?

**Comment by alexneo2003** [comment]
read full text!
<img width="752" alt="Screenshot 2023-04-20 at 11 52 21" src="https://user-images.githubusercontent.com/11705902/233313498-fe5490b9-91ad-448f-a4c3-82b72e71f960.png">

"must register an ID" - thats mean - add you TC ID from ADO to test title in you project - like 
```ts
test('[1] First Test', () => {
    expect(true).toBe(true);
  });
  ```
`[1]` - this is part with you TC ID

**Comment by ravindrakumar6** [comment]
sorry for blocking application names and company names i don't want violate policies hope you understand

**Comment by ravindrakumar6** [comment]
So above screenshots i hope i'm following correctly

**Comment by alexneo2003** [comment]
all looks fine but i can't understand what happened there

and your `suiteId` does'n make sense in config, reporter config doesn't containing `suiteId` parameters

**Comment by ravindrakumar6** [comment]
@alexneo2003 , Hey Alex i removed that suiteId though it's not impacting anything. But after checking further many things
this is what i found , if you see below screenshot "automated = false" but workitem property automation status = Automated,
Let me try one thing i will try to update this value automated = true then if it works will let u know .. uffff
![image](https://user-images.githubusercontent.com/104666900/233334151-ae0f9c88-6298-4f17-b7b3-445fb0af889d.png)

**Comment by ravindrakumar6** [comment]
Hi @alexneo2003 , this is what i found  let me try and do something 
i guess this value automated = true should be there is that correct ?

![image](https://user-images.githubusercontent.com/104666900/233334979-0875fa64-3978-4a2f-8dea-195de2a119c7.png)

**Comment by ravindrakumar6** [comment]
@alexneo2003 , no luck 

So can you help me any of these 3 solution how to make it to work

Test result publishing fails with "Mismatch in automation status of test case and test run"
Azure DevOps (ADO) collects test execution results in Test Runs. Test runs can be either manual or automated. Automated test runs can only contain automated tests (Test Cases marked as "automated") while manual Test Runs can contain any Test Cases. The error message is provided by ADO when a non-automated Test Case is being added to the Test Run.
By default SpecSync sets both the Test Run and the Test Case automation status base on the configuration setting [synchronization/automation/enabled](https://github.com/specsync/reference/configuration/configuration-synchronization/configuration-synchronization-automation). (see [Mark Test Cases as Automated](https://github.com/specsync/features/push-features/mark-test-cases-as-automated)) This means that if the same scenarios were synchronized by SpecSync then the ones that were executed in the test result file, such conflict cannot happen.
Cause: It can happen that some scenarios are excluded from the "automated" status using the [synchronization/automation/condition](https://github.com/specsync/reference/configuration/configuration-synchronization/configuration-synchronization-automation) or [synchronization/automation/skipForTags](https://github.com/specsync/reference/configuration/configuration-synchronization/configuration-synchronization-automation)configuration setting, but they were still included in the test result.
Solution 1: Make sure that the Test Cases the test result belongs to have been successfully synchronized before publishing the test results with the same automation setting.
Solution 2: Try excluding the non-automated scenarios from the test execution
Solution 3: Override the run type setting of the created Test Run using the publishTestResults/runType configuration setting. This setting is available from SpecSync v3.1. For earlier SpecSync versions, create a separate SpecSync config file for test result publishing that sets synchronization/automation/enabled to false. (You can use the [toolSettings/parentConfig](https://github.com/specsync/reference/configuration/configuration-toolsettings) setting to make an [inherited configuration file](https://github.com/specsync/features/general-features/hierarchical-configuration-files), so that you don't need to duplicate all configuration setting.)

**Comment by alexneo2003** [comment]
> @alexneo2003 , no luck
> 
> So can you help me any of these 3 solution how to make it to work
> 

i'm don't understand why they not working
i'm have test runs where TC wasn't automated but my run was successfulled

**Comment by ravindrakumar6** [comment]
ok sure let me keep trying, if i find a solution will ping 👍
