### ISSUE TITLE
having a test case id in the test.describe section

### ISSUE THREAD

**Issue by Jannik-KJ** [alexneo2003/playwright-azure-reporter#32]
It would be nice if you could group different tests and have the common test case id on the test.describe('[123] Test name', () => {})

**Comment by alexneo2003** [comment]
[describe](https://playwright.dev/docs/api/class-test#test-describe-1) is only group of tests, it not test
if you want to group different test in one i think you need to see [test step](https://playwright.dev/docs/api/class-test#test-step)

**Comment by Jannik-KJ** [comment]
I have a test which test different api scenarios on the same page. These are split into different tests but is grouped within a test.descripe as it tests the complete e2e user flow

**Comment by alexneo2003** [comment]
i understand what you do.
pw describe doesn't report any information about describe after it ending. if nothing reporting - nothing publish to azure.
i recomend you using test with including test steps for each TC from azure
