### ISSUE TITLE
[Feature] Set test case to automated

### ISSUE THREAD

**Issue by axtherlov** [alexneo2003/playwright-azure-reporter#33]
Hi,
 First of all, thanks for creating this project. it works great

I'd like to request the ability to associate azure test cases with playwright automated tests. at a glance this might look like out of scope of the project, but this is extremely useful to gather automation test coverage for UI Tests which provides value in the team, so would appreciate if you can consider it

the process consists in calling an Azure API to create or update an association https://dev.azure.com/{organization}/{project}/_apis/wit/workitems/{id}?api-version=7.0  (more info https://learn.microsoft.com/en-us/rest/api/azure/devops/wit/work-items/update?view=azure-devops-rest-7.0&tabs=HTTP)

request body example: this changes manual to automated to a test case with the following values:
[
  {
    "op": "add",  ("add" to new association  "replace" to update existing association)
    "path": "/fields/Microsoft.VSTS.TCM.AutomatedTestName",
    "value": "CreateUser"
  },
  {
    "op": "add", ("add" to new association  "replace" to update existing  association)
    "path": "/fields/Microsoft.VSTS.TCM.AutomatedTestStorage",
    "value": "FrontEndAppName"
  },
  {  //ignore this in case of updating existing association
    "op": "add",  
    "path": "/fields/Microsoft.VSTS.TCM.AutomatedTestId",
    "value": "NewGuid"
  }
]

Attached is an example of how would look like:

![image](https://github.com/alexneo2003/playwright-azure-reporter/assets/47370422/ee166a3b-6718-4b22-91f8-4835981ef96a)

**Comment by alexneo2003** [comment]
can you explain what are want to do?
i know how working API request but i can't understand how you want use it with reporter

**Comment by axtherlov** [comment]
The azure TestRun created by the reporter is great as it also reflects testResults for the ConfigurationIds provided, however, the azure test cases still remain as manual 

By adding the feature requested above, the test cases could automatically become automated. Allowing to create more descriptive graphs in the azure dashboard (which reflect how many automated tests we have vs manual ones)

Attached is an example of what can be done if the feature is added

![image](https://github.com/alexneo2003/playwright-azure-reporter/assets/47370422/fcbb00b1-aebd-44b9-9e2b-27384494e376)

**Comment by alexneo2003** [comment]
in my opinion this "feature" is not related with current reporter
you welcome to write you own "feature" and use it like reporter functionality
if you don't known how it to do - i do it for you (but it not tested!!!)
use it like you use playwright-azure-reporter

```typescript
/* eslint-disable @typescript-eslint/no-empty-function */
import { FullConfig, Reporter, Suite, TestCase } from '@playwright/test/reporter'
import * as azdev from 'azure-devops-node-api'
import { WebApi } from 'azure-devops-node-api'
import { IWorkItemTrackingApi } from 'azure-devops-node-api/WorkItemTrackingApi'
import { IRequestOptions } from 'azure-devops-node-api/interfaces/common/VsoBaseInterfaces'

export default class SetAutomationReporter implements Reporter {
	private connection!: WebApi
	private orgUrl!: string
	private token = ''
	private workItemApi!: IWorkItemTrackingApi
	private azureClientOptions = {
		allowRetries: true,
		maxRetries: 20
	} as IRequestOptions

	constructor(options: any) {
		this.orgUrl = options.orgUrl
		this.token = options.token
		this.connection = new azdev.WebApi(
			this.orgUrl,
			azdev.getPersonalAccessTokenHandler(this.token),
			this.azureClientOptions
		)
	}

	async onBegin(config: FullConfig, suite: Suite) {
		this.workItemApi = await this.connection.getWorkItemTrackingApi()
	}

	async onTestBegin(test: TestCase) {
		const caseIds = this._getCaseIds(test)
		if (!this.workItemApi) {
			this.workItemApi = await this.connection.getWorkItemTrackingApi()
		}
		if (caseIds.length === 0) {
			return
		}
		if (caseIds.length > 1) {
			throw new Error(`Found more than one test case id in test title: ${test.title}`)
		}

		const workItem = await this.workItemApi.getWorkItem(Number(caseIds[0]), ['Microsoft.VSTS.TCM.AutomationStatus'])

		if (workItem.fields?.['Microsoft.VSTS.TCM.AutomationStatus'] === 'Not Automated') {
			const patchDocument = [
				{
					op: 'add',
					path: '/fields/Microsoft.VSTS.TCM.AutomationStatus',
					value: 'Automated'
				}
			]
			await this.workItemApi.updateWorkItem({}, patchDocument, workItem.id as number)
		}
	}

	async onTestEnd(test: TestCase) {}

	async onEnd() {
		this._log('onEnd')
	}

	private _getCaseIds(test: TestCase): string[] {
		const result: string[] = []
		const regex = new RegExp(/\[([\d,\s]+)\]/, 'gm')
		const matchesAll = test.title.matchAll(regex)
		const matches = [...matchesAll].map((match) => match[1])
		matches.forEach((match) => {
			const ids = match.split(',').map((id) => id.trim())
			result.push(...ids)
		})
		return result
	}

	private _log(message: any) {
		console.log(`azure: ${message}`)
	}
}
```
