### ISSUE TITLE
No Test Point Found

### ISSUE THREAD

**Issue by ShouptikDeyIllumina** [alexneo2003/playwright-azure-reporter#34]
Hi,
When i setup my project with all the details i am getting this **No Test Point found** Error. I have double checked my Test Plan ID and Test Case ID they are correct i am not sure why i am getting this error. Can anyone pls help me to understand what i am doing wrong?

![image](https://github.com/alexneo2003/playwright-azure-reporter/assets/135975495/12e09fb9-f5e9-432b-aad9-ffb0163289fa)

I have removed the token and omitted some data while taking the Screenshot. but while running all the data was there.

![image](https://github.com/alexneo2003/playwright-azure-reporter/assets/135975495/e7dc2392-7fab-480b-b59c-a38fd33d70af)

**Comment by alexneo2003** [comment]
can you make request?
url - https://dev.azure.com/{{company}}/{{project}}/_apis/test/points?api-version=7.1-preview.2
body
```json
{
    "pointsFilter": {
        "testcaseIds": [
            3323606
        ]
    }
}
```

in response should be all of test points matched to TestCase id
check all of them - some one should be matched by `configuration: id` and `testPlan: id` with configured you

**Comment by ShouptikDeyIllumina** [comment]
> 
I have made a POST request through postman with Barrer token : PAT. But i am getting this error

![image](https://github.com/alexneo2003/playwright-azure-reporter/assets/135975495/1cb0cd07-efe6-4984-abf6-14d9e1e47eda)

**Comment by alexneo2003** [comment]
> I have made a POST request through postman with Barrer token : PAT. But i am getting this error

first you need convert you token to base64 with extra info with next command
```bash
echo -n “ :YOUR_PAT_GOES_HERE" | base64
         ^
         space + :
```
and set it in header
```bash
Authorization: Basic GENERATED_BASE64
```

**Comment by ShouptikDeyIllumina** [comment]
yes ,Got the api response, There are few configuration ID I have found. attached a screenshot. what should i do with this ID? Should i use this id [configuration ID] in the testcase?
![image](https://github.com/alexneo2003/playwright-azure-reporter/assets/135975495/6d849564-2683-4e8a-b6fd-5600cf33697a)

**Comment by alexneo2003** [comment]
great
now you need to read readme 
```md
// the configuration ids of this test run, use 
// https://dev.azure.com/{organization}/{project}/_apis/test/configurations to get the ids of  your project.
// if multiple configuration ids are used in one run a testPointMapper should be used to pick the correct one, 
// otherwise the results are pushed to all.
configurationIds: [ 1 ],
```
and do what they ask you

**Comment by alexneo2003** [comment]
@ShouptikDeyIllumina any updates?

**Comment by ShouptikDeyIllumina** [comment]
> @ShouptikDeyIllumina any updates?

Hi @alexneo2003 Thanks for your help. It works and i understood well. Just one question i have. we are using PAT for authentication. Can we use appID, Tenant ID , Client name for auth instead of PAT? is it possible on your report?

**Comment by alexneo2003** [comment]
for working with azure api used [azure-devops-node-api](https://github.com/microsoft/azure-devops-node-api/) and using authentication which they provided
