### ISSUE TITLE
A potentially dangerous Request.Path value was detected

### ISSUE THREAD

**Issue by Oscaruzzo** [alexneo2003/playwright-azure-reporter#37]
Hi I'm trying your reporter, it looks very very promising but I'm getting this error. 

URLs and token are correctly configured. Any suggestion? Thank you!

azure: {"$id":"1","innerException":null,"message":"A potentially dangerous Request.Path value was detected from the client (:).","typeName":"System.Web.HttpException, System.Web","typeKey":"HttpException","errorCode":0,"eventId":0}
azure: Failed to create test run. Reporting is disabled.

**Comment by alexneo2003** [comment]
Can you show you config, plz

ср, 5 лип. 2023, 19:07 користувач Oscaruzzo ***@***.***> пише:

**Comment by Oscaruzzo** [comment]
My bad, I had the complete project url in the projectName property instead of the . You can close the issue, sorry for the noise.
