### ISSUE TITLE
Doesn’t reset the status to pass once it is fail or blocked

### ISSUE THREAD

**Issue by mechandan** [alexneo2003/playwright-azure-reporter#41]
@alexneo2003  Seems like there is a bug where if the test case once fail / blocked n in next run its passes , the status of the test case remains fail / block though in actual it is pass 

steps to reproduce : 
1. Execute the test which fail in execution.
2. Test status in ADO is fail ( thats fine )
3. Fix the test case and run it again , this time test is passing

Expected Result :- the failed test case status should change from fail to pass

Actual result : Remains Fail

**Comment by mechandan** [comment]
@alexneo2003  may i ask the difference between testRest n testRun that we pass in config ?? It’s happening when we pass testRun

**Comment by alexneo2003** [comment]
> @alexneo2003 may i ask the difference between testRest n testRun that we pass in config ?? It’s happening when we pass testRun

can you check that your TestCase id, with what it happens, unique in you project and not using twice somewhere in another test

**Comment by mechandan** [comment]
Yes , some of the test case ids were same , but shouldnt it get override by the latest test case run

**Comment by alexneo2003** [comment]
> Yes , some of the test case ids were same , but shouldnt it get override by the latest test case run

Pls, read readme about `testRun` config parameter
