### ISSUE TITLE
getting error azure: Failed to create test run. Reporting is disabled on azure pipeline

### ISSUE THREAD

**Issue by keyvan1996** [alexneo2003/playwright-azure-reporter#43]
been trying to fix this issue for while but I cant figure it out so reaching out for help!
set up playwright-azure-reporter in my project and I am able to report to the test cases when I run them on my laptop (locally). but when the tests are being run on azure pipeline, I'm getting the following error! do you know what the issue might be?
azure: Failed to create test run. Reporting is disabled.

**Comment by alexneo2003** [comment]
Read full message of error, they said that `connect ETIMEDOUT ip address`
I guess that you pipeline doesn't have access to this IP
