### ISSUE TITLE
Question: System.AccessToken usage

### ISSUE THREAD

**Issue by molinch** [alexneo2003/playwright-azure-reporter#44]
Thanks Alex for the library it is really useful. Would you know if it is possible to configure the pipeline so we would leverage System.AccessToken and not a PAT? Otherwise maybe a service connection?

**Comment by alexneo2003** [comment]
for connection with ADO reporter used [azure-devops-node-api](https://github.com/microsoft/azure-devops-node-api) and used [connection flow](https://github.com/microsoft/azure-devops-node-api#create-a-connection) provided there
