### ISSUE TITLE
SyntaxError when catching error

### ISSUE THREAD

**Issue by Coada** [alexneo2003/playwright-azure-reporter#45]
Thanks for this great library!

The exception handling when the testApi fails assumes that the caught error message is encoded using JSON. You should probably decode the message depending on the `Content-Type` response header. In my case I did not have access to ADO which results in a non-JSON exception:

```
> npx playwright test --headed
azure: [1] has title - passed
azure: get started link - passed
azure: Failed to create test run. Reporting is disabled.
undefined:1
connect ETIMEDOUT 13.107.42.20:443
^

SyntaxError: Unexpected token c in JSON at position 0
    at JSON.parse (<anonymous>)
    at AzureDevOpsReporter.onBegin (C:\Users\SEPACOA\workspace\playwright.ts\node_modules\@alex_neo\playwright-azure-reporter\src\playwright-azure-reporter.ts:265:34)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.17.1
```

Additionally, would you be able to provide this library (and instructions) for JavaScript projects too?

**Comment by alexneo2003** [comment]
This error provided from [azure-devops-node-api](https://github.com/microsoft/azure-devops-node-api) package and i can't do any with it
