### ISSUE TITLE
Trouble using testPointMapper

### ISSUE THREAD

**Issue by joeflan** [alexneo2003/playwright-azure-reporter#48]
I'm trying to get the testPointMapper to work when we run two browsers at once that are separated by Project. I have multiple configurations assigned to a test case in my Azure Test Plan. If I manually set the `configurationIds` to use both of the configurations it will find both of them and upload the results to both configurations.

![image](https://github.com/alexneo2003/playwright-azure-reporter/assets/15068380/6b46a6bd-575f-45f1-ae92-ef0cc11aca03)

As soon as I include the `testPointMapper` logic I get the following error:

![image](https://github.com/alexneo2003/playwright-azure-reporter/assets/15068380/759e5216-ac16-4cf3-8e1c-37dc48f3cc52)

I'm sure I'm just configuring the `testPointMapper` and `configurationIds` incorrectly in my config but I don't understand what's wrong. Thanks!

```ts
    [
      '@alex_neo/playwright-azure-reporter',
      {
        orgUrl: MY_ORG,
        token: process.env.AZURE_TOKEN,
        planId: MY_PLANID,
        projectName: MY_PROJECTNAME,
        environment: MY_ENV,
        logging: false,
        testRunTitle: MY_TESTRUNTITLE,
        publishTestResultsMode: 'testRun',
        uploadAttachments: true,
        attachmentsType: ['trace'],
        testPointMapper: async (testCase: TestCase, testPoints: TestPoint[]) => {
          switch(testCase.parent.project()?.use.browserName) {
            case 'chromium':
              return testPoints.filter((testPoint) => testPoint.configuration.id === '65');
            case 'firefox':
              return testPoints.filter((testPoint) => testPoint.configuration.id === '66');
            default:
              throw new Error("Invalid test configuration!");
          }
        },
        testRunConfig: {
          owner: {
            displayName: MY_NAME',
          },
          comment: MY_COMMENT,
          configurationIds: [65,66],
        },
      } as AzureReporterOptions,
    ],
```

**Comment by joeflan** [comment]
I figured this out just now actually, I had to specify the `browserName` in my project to match the switch statement

**Comment by mbielski** [comment]
For those that read this and don't quite get it, the change to the 'projects' section looks like this:

`    projects: JSON.parse(process.env.CI!) ? [
        {
          name: 'Chrome',
          use: { ...devices['Desktop Chrome'], channel: 'chrome', browserName:'chromium' },
        },`
