### ISSUE TITLE
not able to find the attachment, which folder is it looking ?

### ISSUE THREAD

**Issue by msbhatt2018** [alexneo2003/playwright-azure-reporter#49]
not able to find the attachment, which folder is it looking ?

**Comment by alexneo2003** [comment]
Are you sure that you correct use this reporter? :-)

**Comment by jmarti326** [comment]
I might have the same problem, I am reading the doc, but seems like I am not able to figure it out.

`[
      '@alex_neo/playwright-azure-reporter',
      {
        orgUrl: 'https://dev.azure.com/jm',
        token: '#{token}#', 
        planId: 1193,
        projectName: 'PartsUnlimited',
        environment: 'QA',
        logging: true,
        testRunTitle: 'Playwright Test Run',
        publishTestResultsMode: 'testResult',
        uploadAttachments: true,
        attachmentsType: ['screenshot', 'video', 'trace'],
        testRunConfig: {
          owner: {
            displayName: 'JM',
          },
          comment: 'Playwright Test Run',
          // the configuration ids of this test run, use 
          // https://dev.azure.com/{organization}/{project}/_apis/test/configurations to get the ids of  your project.
          // if multiple configuration ids are used in one run a testPointMapper should be used to pick the correct one, 
          // otherwise the results are pushed to all.
          configurationIds: [ ],
        },`

**Comment by jmarti326** [comment]
You were totally right! I wasn't event turning on videos and screenshots on the config. Appreciate it! Awesome library!
