### ISSUE TITLE
[Question] How to correctly links test with complex configurations ?

### ISSUE THREAD

**Issue by Az8th** [alexneo2003/playwright-azure-reporter#50]
I have a need to run tests not only on different browsers, but also on different operating systems. Hence I made a configuration in Azure DevOps for each relevant combo.
So my question is : has anyone found a clean way to correctly link bi-dimentional configurations using testPointMapper ?

For example : Windows + Firefox / Windows + Chrome / Android + Chrome / Mac + Safari / Mac + Firefox / Linux + Firefox / Linux + Chrome

**Comment by alexneo2003** [comment]
how about to use environment variables?
