### ISSUE TITLE
[Bug/Suggestion] Entire report publishing skipped if only one ID is invalid

### ISSUE THREAD

**Issue by Az8th** [alexneo2003/playwright-azure-reporter#51]
Not sure if it is a bug, but if a test is associated with an unexisting ID, even if a comprehensive error message is displayed, it cancels the entire publishing and ignore all valid tests, rather than just skipping the invalid one and publish.

```
azure: Using run 51 to publish test results
azure: Start publishing test results for 44 test(s)
azure: Invalid test configuration!
azure: No test points found for test case [101] associated with test plan 31. Check, maybe testPlanId, what you specified, is incorrect.
azure: Test results published for 0 test(s)
azure: Run 51 - Completed
```

**Comment by alexneo2003** [comment]
`azure: Invalid test configuration!`
maybe you got `testPointMapper` config from readme example? please pay attention that it contain throw Error!!
  ```typescript
testPointMapper: async (testCase: TestCase, testPoints: TestPoint[]) => {
    switch(testCase.parent.project()?.use.browserName) {
      case 'chromium':
        return testPoints.filter((testPoint) => testPoint.configuration.id === '3');
      case 'firefox':
        return testPoints.filter((testPoint) => testPoint.configuration.id === '4');
      case 'webkit':
        return testPoints.filter((testPoint) => testPoint.configuration.id === '5');
      default:
        throw new Error("invalid test configuration!");
    }
  }
```

**Comment by Az8th** [comment]
This is effectively what causes the problem, thanks.
By the way `testCase.parent.project()?.use.browserName` returns `undefined`, did I missed something for the configuration ?

**Comment by alexneo2003** [comment]
> This is effectively what causes the problem, thanks. By the way `testCase.parent.project()?.use.browserName` returns `undefined`, did I missed something for the configuration ?

read [this](https://github.com/alexneo2003/playwright-azure-reporter/issues/48#issuecomment-1775869186), pls

**Comment by Az8th** [comment]
Effectively, I forgot to declare it, then throwing an error and aborting the publishing. I both switched `publishTestResultsMode` to `testResult` and used the project name in the switch instead (`switch(testCase.parent.project()?.name)`), as the playwright doc examples have for project name each browser.

Thanks for your help, :D

Nevertheless, it seems I still stepped on two strange behaviours 😅
1. This one may be due to Azure DevOps, but tests that are in 'fixme' mode are not shown when clicking their execution log from test plans, despite being displayed as 'supsended' in the test suite list.

2. I still have an error for each test to be reported as not in the test plan, despite actually updating passing or failing tests. Which is not due to a bad token, as it succesfully produce a test run, proving it can access the API, I also triple checked the testPlanId, which is corrrect and was not mistaken with the suiteID.
```
azure: No test points found for test case [1] associated with test plan 31. Check, maybe testPlanId, what you specified, is incorrect.
azure: No test points found for test case [2] associated with test plan 31. Check, maybe testPlanId, what you specified, is incorrect.
[...]
azure: No test points found for test case [59] associated with test plan 31. Check, maybe testPlanId, what you specified, is incorrect.
azure: No test points found for test case [60] associated with test plan 31. Check, maybe testPlanId, what you specified, is incorrect.
```

Also, I use playwright in an Azure pipeline, which creates a test run with attached reports, but using the azure reporter produces a second test run, did I configured it incorrectly, or is there a way to only produce one ?

**Comment by Az8th** [comment]
@alexneo2003 I finally found the problem, I thought configuration were defined globally , but by browsing the API, I understood that they have to be specified for each test.
Still, the error message `azure: No test points found for test case [X] associated with test plan Y. Check, maybe testPlanId, what you specified, is incorrect.` could be more explicit in this precise case ;)

**Comment by alexneo2003** [comment]
read [this](https://github.com/alexneo2003/playwright-azure-reporter/issues/34) issue, pls, and than, I guess, you can figure out how to handle configuration

**Comment by Az8th** [comment]
No worries, as I said, I found the problem and fixed the configuration on the Azure side, thanks !
