### ISSUE TITLE
[Suggestion] Add a token rights section in the docs

### ISSUE THREAD

**Issue by Az8th** [alexneo2003/playwright-azure-reporter#52]
Hello,

Could you add a section on which rights are required for the Azure token please ? I noticed that many users just creates a full access token, which is not very secure.

Thanks ;)

**Comment by alexneo2003** [comment]
everyone decides for himself which settings are suitable for him

**Comment by Az8th** [comment]
This is true, but which ones are actually required to profit from all the reporter functionnalities ?

**Comment by alexneo2003** [comment]
I guess that ADO new token config has not so many config and all of them is very friendly to understand and user will be able to deal with the rights since the rights are clearly indicated - "Test Management - Read, create, and update test plans, cases, and results"
