### ISSUE TITLE
[Question] Test plan is in project A, pipeline is in project B. Can i get cross project pipelineReference?

### ISSUE THREAD

**Issue by pkumanowski** [alexneo2003/playwright-azure-reporter#56]
Hi, I want to reference pipeline in the test report. However my pipeline is in different project than the Test Plans. 
Is there a possibility to do a cross reference? 

BTW, thanks for this project it helped me a lot.

**Comment by alexneo2003** [comment]
Sorry, but I haven't experience with cross project work. Only with multiple plans inside one project.
If you decide to work with plans - you can define one "automation" plan and link test cases from multiple plans to one

**Comment by pkumanowski** [comment]
Ok, so I'll close this question. Thanks for input!
