### ISSUE TITLE
configurationIds: Error logs when test case does not have proper assigned configurations in Azure

### ISSUE THREAD

**Issue by melkorinos** [alexneo2003/playwright-azure-reporter#57]
Hi, thank you for the great package, helps me a lot.

I was trying to get my test results posted but i was getting this error.  The error suggests that the issue is between the test case and the test plan. 

However, the actual issue was that i was passing a `test configuration` in `AzureReporterOptions` that was not properly assigned to the test case in azure. I was thinking the error message could be improved? Cheers :)

https://dev.azure.com/XXX/XXX/_testPlans -> Right click on a test plan/case -> Assign configuration

```
azure: Start publishing test results for 1 test(s)
azure: No test points found for test case [107222] associated with test plan 75767. Check, maybe testPlanId, what you specified, is incorrect.
azure: Test results published for 0 test(s)
azure: Run 1736182 - Completed
```

To be clear, the error message is correct. My configuration was wrong. But the fact that it did not mention the `test configurations`  kind of through me on the wrong path.

**Comment by alexneo2003** [comment]
read this issue #34 probably it help you
if not - pls come back

**Comment by melkorinos** [comment]
Hey, all is good with my setup, it works fine :)
You can mark this ticket as closed. I just wanted to note that IMO the error message should be expanded a little. 
But again, great addon and it works fine as well :)

**From** : No test points found for test case [107222] associated with test plan 75767. Check, maybe testPlanId, what you specified, is incorrect.

**To** : No test points found for test case [XXX] associated with test plan XXX` for configuration(s) XX`. Check, maybe testPlanId `or assigned configurations per test case`, what you specified, is incorrect.

**Comment by Az8th** [comment]
As I already faced the same problem and mentioned it in a comment of #51 (https://github.com/alexneo2003/playwright-azure-reporter/issues/51#issuecomment-1803877759_), I support that a more explicit error message is needed here.
