### ISSUE TITLE
Test Run Data - Execution History, not showing up

### ISSUE THREAD

**Issue by PagelsR** [alexneo2003/playwright-azure-reporter#58]
Hi @alexneo2003 , I'm hoping you can point me in the right direction.  I'm using your Playwright Azure Reporter and I think i have everything configured correctly.  Per your setup docs, I'm running many PlayWright tests written in TypeScript from ADO pipelines.  The test results get posted to the "Test Run" tab on "Test Plans", works great!  The #of tests pass or failing, get posted to the Pipeline run, works great!  What I do not see is any data for the individual Test Case ID run, right click on test case “View Execution History”.

My question is, am I supposed too?

I'd love to see a working version of this.

Thank you in advance.
Randy

**Comment by alexneo2003** [comment]
Hi.
Sorry, but I don't know why it won't work for you. For me it work as expected, I can see executions history

![Screenshot_2024-02-23-19-38-56-45_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/alexneo2003/playwright-azure-reporter/assets/11705902/5a9de563-1f3f-4713-a972-d698cc4e4dfe)

**Comment by PagelsR** [comment]
That's awesome and 100% what I'm expecting to see.  Hmmm?  

Where in ADO are you looking at this list "Test Case Results"?  Maybe I'm looking in the wrong place. From Test Plans, Runs? From Build Pipeline output?

Does the ADO Token need to have FULL scope permissions?

**Comment by PagelsR** [comment]
Does your Progress Report also get updated?  Mine does not, not from any automation.

<img width="388" alt="image" src="https://github.com/alexneo2003/playwright-azure-reporter/assets/4490855/424ca1ed-b054-40e3-96f0-4f1511e2bcc4">

**Comment by alexneo2003** [comment]
@PagelsR sorry for delay
I open history from Test Plan - Test Case - More options - View executions history
Also I have not so perfect testcases)
<img width="334" alt="Screenshot 2024-02-27 at 10 32 15" src="https://github.com/alexneo2003/playwright-azure-reporter/assets/11705902/3c7256af-bddd-468d-874c-c0d47419313f">

and also I have "Progress report"
<img width="998" alt="Screenshot 2024-02-27 at 10 32 46" src="https://github.com/alexneo2003/playwright-azure-reporter/assets/11705902/2a7f92fa-25d0-4a5c-b240-b6079a27d7f8">


Can you check pipeline log? It should be contain log like "azure: Result published: {test case title}"

**Comment by PagelsR** [comment]
So strange for sure.  My Tests run successfully and results say they published.  When I look at Execution History, I might see a few results.

<img width="697" alt="Screenshot 2024-03-02 142940" src="https://github.com/alexneo2003/playwright-azure-reporter/assets/4490855/bb767253-eb79-4580-8bb3-28fc6532d129">

I've run my pipeline dozens of times since Feb 8, so inconsistent.
<img width="299" alt="Screenshot 2024-03-02 143513" src="https://github.com/alexneo2003/playwright-azure-reporter/assets/4490855/563ef0e8-6c78-46cf-8c95-0ba715ba9085">

I love how your progress report gets updated too, nice!!!

Is there any chance any way, you can give me "reader" on access to a ADO Team Project with all of thi working? Give to "pagelsr@live.com" account.  Then maybe I can view how your setup is.  If not, no worries.

Thank you Alex for the help.

**Comment by alexneo2003** [comment]
@PagelsR are you sure that you use correct package and steps to publish test results to ADO. because what I see does not correspond to the logs from this package, something else!

**Comment by PagelsR** [comment]
I will start over and try again.  Here is my pipeline and how I'm publishing results, got an example of your YML?

<img width="329" alt="image" src="https://github.com/alexneo2003/playwright-azure-reporter/assets/4490855/b23329da-436d-4ae5-8ec4-0b10207b9295">

**Comment by alexneo2003** [comment]
@PagelsR  let me ask you again - **are you sure that you use correct package and steps to publish test results to ADO**
because you doesn't use **THIS** package!! you used "PublishTestResults@2" task - it's ADO task, not mine package!

**Comment by PagelsR** [comment]
I'm sure you're right, so I'll need to start over. Very strange for sure, I'm following your post (https://www.npmjs.com/package/@alex_neo/playwright-azure-reporter) to the letter.

The only pipeline command is "npx playwright test". 

My used publish command isn't necessary I guess.

**Comment by PagelsR** [comment]
Make me wonder if the ADO Org I created a Token from, is blocking updates.

**Comment by alexneo2003** [comment]
> Very strange for sure, I'm following your [post](https://www.npmjs.com/package/@alex_neo/playwright-azure-reporter) to the letter.

maybe you weren't very careful but readme doesn't contain any things about pipeline
you used one thing but thought about another

for use this package for publishing test results you need to configure reporter section inside playwright.config.ts file and you test results will be published together with test run

**Comment by PagelsR** [comment]
Success!!!

Created new PAT, scope = Build, Release, and Test Management. I think this fixed it.  But just in case, I changed token name to "AZURE_TOKEN", updated in playwright.config.ts file. Added to pipeline as variable.  Done! now works like a charm, execution history, test runs, and report.

Thank you so much for the help Alex!
