### ISSUE TITLE
[Question] Possible to continue to see console output with playwright-azure-reporter enabled?

### ISSUE THREAD

**Issue by awha86** [alexneo2003/playwright-azure-reporter#59]
Hi, thank you for a great package!

When enabling playwright-azure-reporter in playwright.config.ts, the normal console output seems to be hidden/overwritten by the reporter.

Without playwright-azure-reporter configured:
![image](https://github.com/alexneo2003/playwright-azure-reporter/assets/17437445/91427b4f-4644-4633-86e4-cc6e0217ebd4)

With playwright-azure-reporter configured:
![image](https://github.com/alexneo2003/playwright-azure-reporter/assets/17437445/07b03f58-f431-4e78-b4cd-f7a8f831eca1)

Is there a way to disable this behavior? Setting logging: true in the config didnt do it.

**Comment by alexneo2003** [comment]
@awha86 
as you can see in [readme](https://github.com/alexneo2003/playwright-azure-reporter?tab=readme-ov-file#configuration) config `logging` is disabled by default 
> - `logging` [true/false] - Enabled debug logging from reporter or not. Default: `false`.

And when you setup logging: true on the contrary, you enable this configuration

**Comment by awha86** [comment]
@alexneo2003 
Thank you for the quick reply.

My point is that just having the reporter configured, even if I have enable logging or not, I don't see console output anymore:

logging disabled:
![image](https://github.com/alexneo2003/playwright-azure-reporter/assets/17437445/83234745-81f6-4f57-a949-77b65c2e7f1f)

logging enabled:
![image](https://github.com/alexneo2003/playwright-azure-reporter/assets/17437445/26d0e2b6-7b94-43b7-a9ee-cac2d53d932b)

playwright-azure-reporter commented out (removed) of playwright.config.ts:
![image](https://github.com/alexneo2003/playwright-azure-reporter/assets/17437445/cfa988be-f878-4acb-8c1a-f978c39920b7)

**Comment by alexneo2003** [comment]
what are you use as logger?

**Comment by awha86** [comment]
Just the basic stdout for console.log().  
I am not sure if its relevant, but I have the playwright html reporter & a junit reporter configured in the project aswell: 
![image](https://github.com/alexneo2003/playwright-azure-reporter/assets/17437445/f22675e2-5264-48f4-8484-7d0710c7aa76)

**Comment by alexneo2003** [comment]
I'm so sorry but really I don't know why it's happens.
For logs in reporter we use [debug](https://github.com/debug-js/debug) package and, mayby, it has conflict with console.log, I don't know.
I try to reproduce this issue in my own project but it doesn't reproduced

**Comment by awha86** [comment]
Thanks for investigating. Its not a major issue, just an annoyance. 
Should I close this or keep it open?
