### ISSUE TITLE
[Feature] Automatically set ADO configuration value for executed test cases

### ISSUE THREAD

**Issue by z0n** [alexneo2003/playwright-azure-reporter#6]
Hi, first of all thanks for this reporter, it's super useful!

I'm very new to Azure DevOps and noticed it's possible to set configuration options for test plans:  
![image](https://user-images.githubusercontent.com/7430908/195552801-51603e48-877f-4ddf-a761-7b4b5a2d5072.png)

Is it possible to apply/create them dynamically and assign them to the executed test cases?  
Right now, it always sets the default configuration for each test case:  
![image](https://user-images.githubusercontent.com/7430908/195553377-8dd5194c-1f87-49d1-b55f-58222279bd59.png)

I run the tests in three browsers and it's hard to see which browser was used for each test right now. It would be great to see the browser name in the configuration column there.

**Comment by alexneo2003** [comment]
Hi, thanks for the feedback.

You can try beta package 
`npm install @alex_neo/playwright-azure-reporter@1.2.0-beta.0
`
here i'm adding ability to extend test run data when it creating
 ``` ts
[
      './src/playwright-azure-reporter.ts',
      {
        orgUrl: azureConfig.orgUrl,
        token: azureConfig.token,
        planId: azureConfig.testPlanId,
        projectName: azureConfig.projectName,
        environment: 'AQA',
        testRunTitle: 'Playwright Test Run',
        uploadAttachments: true,
        logging: true,
        attachmentsType: ['screenshot'],
        testRunConfig: {
          owner: {
            displayName: 'Alex Neo',
          },
          comment: 'Playwright Test Run',
        }
      } as AzureReporterOptions
    ]
```
`testRunConfig` object inside reporter configuration
Read [doc](https://learn.microsoft.com/en-us/rest/api/azure/devops/test/runs/create?view=azure-devops-rest-7.1&tabs=HTTP#request-body) from more information about info what you can pass it

try it and i waiting for feedback

**Comment by z0n** [comment]
Hi, thanks for the quick response. This looks promising, I think what I need is the `configurationIds` parameter which is not yet transmitted (?).

I tried this:  
```ts
testRunConfig: {
    configurationsIds: [42]
}
```
Where 42 is my configuration id:  
![image](https://user-images.githubusercontent.com/7430908/195563052-abd59d6f-b127-4833-8031-7ac47523670f.png)

Still, it shows the default configuration (Windows 8) on all executed test cases.

**Comment by alexneo2003** [comment]
> I tried this:
> 
> ```ts
> testRunConfig: {
>     configurationsIds: [42]
> }
> ```
1. you pass incorrect variable, correct - `configurationIds`
2. try `@alex_neo/playwright-azure-reporter@1.2.0-beta.1`. I previously exclude configurationIds from config and pass default value - `[1]` anyway. at `1.2.0-beta.1` i changing it to be optional

**Comment by z0n** [comment]
Oh wow, I thought I copied it 😄  
With `1.2.0-beta.1`, I get the type hint now. It still shows the default configuration in ADO though, even though I set the ID to one of the others.

**Comment by alexneo2003** [comment]
> Oh wow, I thought I copied it 😄 With `1.2.0-beta.1`, I get the type hint now. It still shows the default configuration in ADO though, even though I set the ID to one of the others.

ok, i think i finding where problem. i need some time to implement it
when i do this - i ping you

**Comment by alexneo2003** [comment]
@z0n 
try this - `@alex_neo/playwright-azure-reporter@1.2.0-beta.2`
if you will setup value `configurationIds` this package trying to find corresponding pointsId by `testPalnId`, `testCaseId` and it mite be included in `configurationIds` - if it is package took it, otherwise - set default value with is [1]

**Comment by z0n** [comment]
Thanks, I'll try it next week!

**Comment by z0n** [comment]
Hi, I tried it with your new version but I'm not sure if I did it right. This is my current reporter config:  
```ts
[
    '@alex_neo/playwright-azure-reporter',
    {
        orgUrl: azureOrgUrl,
        token: azureToken,
        planId: azureTestPlanId,
        projectName: azureProjectName,
        environment: 'Playwright',
        testRunTitle: `Playwright Test Run ${new Date().toISOString()}`,
        uploadAttachments: true,
        attachmentsType: ['screenshot', 'video', 'trace'],
        testRunConfig: {
            configurationIds: [42]
        }
    } as AzureReporterOptions
]
```
`42` is the ID of the configuration I'd like to use.  
However, the default configuration is still used instead that one.  
Do I need to set anything else?

**Comment by alexneo2003** [comment]
@z0n can you text me for debugging - https://t.me/Alex_Neo

**Comment by alexneo2003** [comment]
@z0n hi, man
i'm set configurationIds config and test it 
i'm set not default id and run it
here is what i get

<img width="1079" alt="Monosnap Runs - Test Plans 2022-11-01 16-57-02" src="https://user-images.githubusercontent.com/11705902/199265540-b4ea2ec5-7f7b-4c36-8434-30f81d28cd15.png">


default value is - Windows 11
if you have some questions pls open new issue

**Comment by z0n** [comment]
Hi @alexneo2003, sorry I didn't come back to you, I was busy with other tasks. It works now, I didn't know I had to assign the configurations I wanted to use to the test plan.

Thanks for your work!
