### ISSUE TITLE
[Question] Associate test cases

### ISSUE THREAD

**Issue by taddeuz** [alexneo2003/playwright-azure-reporter#60]
Hi. I just tried the packages and its awesome. I thought about using the DevOps API directly to update my test cases, but with this package it works out of the box. Thanks.

It is possible to set the automation status (status/storage/etc.) as well? I would like to associate my test cases. You already pick the test cases and set the outcome...the association should be not a big deal?

**Comment by alexneo2003** [comment]
check [this](https://github.com/alexneo2003/playwright-azure-reporter/issues/33#issuecomment-1592953570) pls

**Comment by TheEisbaer** [comment]
@alexneo2003 sorry for hopping onto this, are you planning on adding this feature to the reporter anytime (or create a new reporter if that doesn't "fit" into this current one)? :)

**Comment by alexneo2003** [comment]
Hi @TheEisbaer 
Could you pls read the [comment](https://github.com/alexneo2003/playwright-azure-reporter/issues/134#issuecomment-3566822415)
