### ISSUE TITLE
SyntaxError: Unexpected token 'R', "Request ti"... is not valid JSON

### ISSUE THREAD

**Issue by kovacsdongo** [alexneo2003/playwright-azure-reporter#62]
when i want to run i get an error:

azure: Failed to create test run. Reporting is disabled.
undefined:1
Request timeout: /avanderonline/_apis/Location
^

SyntaxError: Unexpected token 'R', "Request ti"... is not valid JSON
    at JSON.parse (<anonymous>)
    at AzureDevOpsReporter.onBegin (C:\git\hydro-test\node_modules\@alex_neo\playwright-azure-reporter\src\playwright-azure-reporter.ts:290:34)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.11.1

**Comment by alexneo2003** [comment]
Hi @kovacsdongo 
Can you read #15 maybe you find some helpful 
and after check your config and come back

**Comment by daniavander** [comment]
thanks the bug label :)

**Comment by alexneo2003** [comment]
it's looks like some issues with Azure API
I checked [Azure status page](https://azure.status.microsoft/en-gb/status) and unfortunately don't see any issues
unfortunately it's not reporter issue
I'm already working on fix to improve errors logging
I leave this issue opened and waiting maybe it will be fixed themself

**Comment by daniavander** [comment]
it's possible that the azure load is high, because yesterday afternoon it went fine several times is effective

**Comment by alexneo2003** [comment]
@kovacsdongo @daniavander 
any updates?

**Comment by daniavander** [comment]
it is working now, perhaps it was an azure issue
thnaks the help
