### ISSUE TITLE
Failing To Report 

### ISSUE THREAD

**Issue by o3-steven** [alexneo2003/playwright-azure-reporter#68]
I'm getting an error that I can't seem to find the root of either in this project or in the azure-devops-api. I'm not sure if you are able to help but this is what I'm receiving in the console

`Azure DevOps Server Identity cannot be found of the user: {Project Name}`

It seems that the PAT is good and that it is attempting the connection. The PAT permissions are Test Management Read and Write. Is there anything else I can do to help with the debug? This is my first time working the devops api so I might be missing something simple here.

**Comment by alexneo2003** [comment]
Can you share your playwright config where you connect this reporter?

**Comment by o3-steven** [comment]
That got me in the right direction thanks. The display name property in owner was my mistake
