### ISSUE TITLE
How to use `AZURE_PW_TEST_RUN_ID`?

### ISSUE THREAD

**Issue by ShaMan123** [alexneo2003/playwright-azure-reporter#69]
I want to add some logging involving `AZURE_PW_TEST_RUN_ID`, e.g. a link to the run UI in azure.
Since onEnd is async the env var is set at some point in time I can't control or hook into.
I have tried reading it upon completion but it will not persist.
I've also tried to pipe the output and use regex to get it from the logs but couldn't achieve that since the process is detached.
Therefore, I do not see how to read it apart from overriding the `onEnd` method:
```
import reporter from "@alex_neo/playwright-azure-reporter";

const onEnd = reporter.prototype.onEnd;
reporter.prototype.onEnd = async function (...args) {
  const retval = await onEnd.apply(this, args);
  console.log("READY:", process.env.AZURE_PW_TEST_RUN_ID);
  process.emit('message', { runId: process.env.AZURE_PW_TEST_RUN_ID }); // inform parent process
  return retval;
};

export default reporter

```

Perhaps I should PR
```
process.emit('message', { runId: process.env.AZURE_PW_TEST_RUN_ID }); // inform parent process
```

And a log of type 
```console.log(
    `URL: ${this._orgUrl.replace("vssps.", "")}/${
      this._projectName
    }/_testManagement/runs?runId=${runId}&_a=resultQuery`
  );
```

**Comment by alexneo2003** [comment]
`AZURE_PW_TEST_RUN_ID` been defined at onBegin hook after TestRun was created and this action also logging in console
How I use it. I need send some report in email after run was finished and in report I'm made TestRun URL, like you, and for that I have created my custom [reporter as it writed in docs](https://playwright.dev/docs/test-reporters#custom-reporters) and took RUN_ID from env like
```typescript
const runId = process.env.AZURE_PW_TEST_RUN_ID
`${this._orgUrl.replace("vssps.", "")}/${this._projectName}/_testManagement/runs?runId=${runId}&_a=resultQuery`
```

**Comment by ShaMan123** [comment]
Thanks, I think I tried that but the reported didn't wait for onEnd to complete since it is async so I couldn't use the env var.
I don't see the env var being set in `onBegin`, only `onEnd`, running with `testResults` not `testRun`.

Singals to the parent process is very simple and allows me to easily add the following the `playwright.config.ts`:
```
process.on('message', ...)
```

**Comment by ShaMan123** [comment]
can be closed

**Comment by ShaMan123** [comment]
Yeah, and since it is async in nature the best thing I thought of doing is hooking into onEnd
Might be worth to expose an onEnd hook that can be passed via the config object
That sounds the best solution to me
