### ISSUE TITLE
How to configure test results publishing to see them in build view

### ISSUE THREAD

**Issue by KaMa75** [alexneo2003/playwright-azure-reporter#7]
Hi. I'm trying to configure this reporter and I can't see results in build view. I have created test plan having one passing and one failure tests. The results are visible in the test plan

![image](https://user-images.githubusercontent.com/43001438/195855072-9af3f5a6-48a9-435d-9296-fbfcf4d4fdca.png)

but in the build view hasn't the results

![image](https://user-images.githubusercontent.com/43001438/195855867-df4c9a58-53a7-4439-8975-4160e25ea60c.png)

Do I need additionaly configure "PublishTestResults" task like [here](https://playwright.dev/docs/ci#azure-pipelines)?

![image](https://user-images.githubusercontent.com/43001438/195856827-ba4b4d15-2a10-4055-ab84-4c2990e35937.png)

Should I use this reporter? When I'm using JUnit reporter the build view has the results, but there are not snapshots attachments.

Can you explain me, how to use this reporter to see test results with attachments in build view?

Thank you in advance.

**Comment by alexneo2003** [comment]
Hi
I don't have much experience to connect test run with build info but you can try beta package `@alex_neo/playwright-azure-reporter@1.2.0-beta.2` where i added extra data to config

 ``` ts
[
      '@alex_neo/playwright-azure-reporter',
      {
        orgUrl: azureConfig.orgUrl,
        token: azureConfig.token,
        planId: azureConfig.testPlanId,
        projectName: azureConfig.projectName,
        environment: 'AQA',
        testRunTitle: 'Playwright Test Run',
        uploadAttachments: true,
        logging: true,
        attachmentsType: ['screenshot'],
        testRunConfig: {
          owner: {
            displayName: 'Alex Neo',
          },
          comment: 'Playwright Test Run',
        }
      } as AzureReporterOptions
    ]
```
`testRunConfig` object inside reporter configuration
Read [doc](https://learn.microsoft.com/en-us/rest/api/azure/devops/test/runs/create?view=azure-devops-rest-7.1&tabs=HTTP#request-body) from more information about info what you can pass it
at this you can pass `build` object which contain info about build, i think it so.

**Comment by alexneo2003** [comment]
I'm looking how working PublishTestResults at pipeline. I'm think pipeline linking results with build in runtime. at now my reporter doesn't have any information about build. if you have any idea how to - I'm listening you

**Comment by KaMa75** [comment]
Ok. Thank you for your response. I'll write if I come up with a nice solution.

**Comment by rovmak** [comment]
Is there any solutions @KaMa75 ? I need to configure test results publishing to see them in build view.
