### ISSUE TITLE
BDD integration help

### ISSUE THREAD

**Issue by AmmarQA24** [alexneo2003/playwright-azure-reporter#70]
We are using https://github.com/vitalets/playwright-bdd/tree/main and need some help with integration to Azure test plans. We can't use @[tc123] format because we will get an error in the feature file, is there any other way for us to send tags without []?

**Comment by AmmarQA24** [comment]
figured it out, but got this one right now and I get empty test results @alexneo2003 
![image](https://github.com/user-attachments/assets/092b76ec-df0d-4a16-87af-4372ae3f0809)

**Comment by vitalets** [comment]
@AmmarQA24 btw, what error do you get with `@[tc123]` tags? 
I've checked on my side - test files are generated and executed.
Like this:
```feature
Feature: Playwright Home Page

    @[tc123]
    Scenario: Check title
        Given I am on Playwright home page
        When I click link "Get started"
        Then I see in title "Installation"
```

**Comment by alexneo2003** [comment]
> Btw is there a way to publish cucumber steps into test case when we run it so we don't have to manually write test case every time and copy paste them? @alexneo2003 

How your imagine it?)

**Comment by AmmarQA24** [comment]
if I have these steps and test case with id tc123 doesn't exist maybe each step would appear as a test case?

Scenario: Create template with 1 security level, create workspace, soft archive, hard archive and delete workspace
        Given User logs in
        When I create template
        Then I validate new template is created
        When I open security menu item from template details
![image](https://github.com/user-attachments/assets/ca48dbb4-27be-485a-a087-15fcff805b07)

**Comment by alexneo2003** [comment]
> if I have these steps and test case with id tc123 doesn't exist maybe each step would appear as a test case?
> 

If you have the described situation maybe you should create related Test Case.

Are you sure that you correct understand of "Test Case" meaning? And difference between "Test Case" and "Test Step"?
