### ISSUE TITLE
Add additional annotations

### ISSUE THREAD

**Issue by quotschmacher** [alexneo2003/playwright-azure-reporter#71]
Is there any possibility to add additional annotations to the test? Playwright itself offers for example the option to us `test.info().annotations.push(...)` to add some more, but it does not appear in the Azure test results.

There are some interesting fields:
![image](https://github.com/user-attachments/assets/a376778e-eab2-4bfd-a2fc-0ff8d80bce61)

Would it be possible to access them somehow? For example to add the actual used browser version or something like that?

**Comment by alexneo2003** [comment]
Look at the reporter config `testRunConfig` section

**Comment by quotschmacher** [comment]
@alexneo2003 I know this section, but as it is located in the configuration-file I do not have access to the exact browser version used in the specific run. Inside the testfile I am able to do something like
```
    test.beforeEach(async ({ loginPage, homepage, browser }) => {
        console.log(`${browser.browserType().name} ${browser.version()}`);
    });
```

what in this case gives me a `firefox 127.0`. But how am I able to print this version to every test run?

**Comment by alexneo2003** [comment]
Inside `testRunConfig` you have parameter `Configuration` - it can be related with browser as Test Case configuration.
That information what you show on your screenshot are placed on higher level than test scope.

**Comment by quotschmacher** [comment]
So then maybe my interpretation of the fields was wrong. Is there any possibility to note the used browser-versions to a specific test run of a specific test id with a specific configuration? At least the configuration does not know if the CI/CD-Pipeline is using a newer version of the browser...

**Comment by alexneo2003** [comment]
sorry but no, I'm don't know how do it
