### ISSUE TITLE
Using reporter with Azure Devops CI

### ISSUE THREAD

**Issue by andreipintilei** [alexneo2003/playwright-azure-reporter#79]
I am using this reporter for my CI in Azure Devops. I created a pipeline in which I  specify the test plan. I have about 61 test cases that run, Until I had like 50 test cases the reporter worked fine. All results appeared in the  test plan. After having more then 50 test cases it does not work anymore. It only populates about 14 test cases with the results and no more. It gives me the error : "azure:pw:warn No test points found for test case [123456] associated with test plan 654321 for configurations [5]
Check, maybe testPlanId or assigned configurations per test case, what you specified, is incorrect. "

But the test is in the test plan and it has the correct configuration. All tests are configured the same, but only 14 get populated. Any ideas?

**Comment by Az8th** [comment]
What is the value of publishTestResultsMode in your config? testResult or testRun ?
If you choosed the latter, you should consider test with the former as a temporary fix ;)

Maybe the AzDO API have a limitation for the number of results it can handle

**Comment by alexneo2003** [comment]
@andreipintilei 
can you read this [comment](https://github.com/alexneo2003/playwright-azure-reporter/issues/34#issuecomment-1593462524) and step by step through API request figure out in which place you miss your results

**Comment by andreipintilei** [comment]
using testResult fixes the issue :) thanks
