### ISSUE TITLE
Handling multiple Plan Ids

### ISSUE THREAD

**Issue by SaiManojKumarYerra** [alexneo2003/playwright-azure-reporter#81]
Hi @alexneo2003 ,

It's probably not an issue with the Azure Playwright reporter itself, but I would like to understand how to manage the Azure Playwright reporter when dealing with multiple plan IDs to consolidate the reports into a single reporter.

Thank You in Advance...

**Comment by alexneo2003** [comment]
If you look at [ADO API docs](https://learn.microsoft.com/en-us/rest/api/azure/devops/test/runs/create?view=azure-devops-rest-7.1&tabs=HTTP#examples) you can find that Test Run should be created only for ONE plan.
If you want handling with few Test Plans I would like to suggest to you use few playwright.config files and/or few projects (including with grep and tag annotations)
