### ISSUE TITLE
 azure:pw:error Failed to create test run. Check your token. Reporting is disabled. +0ms

### ISSUE THREAD

**Issue by sqagithub** [alexneo2003/playwright-azure-reporter#83]
I get this on my local machine after configuration. Any insights?

[
      '@alex_neo/playwright-azure-reporter',
      {
        orgUrl: 'xxxxxx',
        token: process.env.AZURE_DEVOPS_TOKEN,
        planId: 31042,
        isDisabled: false,
        projectName: 'Analytics',
        environment: 'QA',
        logging: true,
        testRunTitle: 'Playwright Test Run',
        publishTestResultsMode: 'testRun',
        uploadAttachments: true,
        attachmentsType: ['screenshot', 'video', 'trace'],
        testCaseIdMatcher: /@\[(\d+)\]/,
        testRunConfig: {
          owner: {
            displayName: '',
          },
          comment: 'Playwright Test Run',
          // the configuration ids of this test run, use
          // https://dev.azure.com/{organization}/{project}/_apis/test/configurations to get the ids of  your project.
          // if multiple configuration ids are used in one run a testPointMapper should be used to pick the correct one,
          // otherwise the results are pushed to all.
          configurationIds: [2],
        },
      } as AzureReporterOptions,
    ],

![image](https://github.com/user-attachments/assets/26a828f4-9fda-411a-9642-2ce50d97071a)

**Comment by alexneo2003** [comment]
I thought that your `projectName` parameter wrong. 
You should get it from URL
`https://dev.azure.com/{organization}/{**project**`}

**Comment by sqagithub** [comment]
I had the correct projectname and that is not the issue.
![image](https://github.com/user-attachments/assets/bacc062a-2503-43ed-b94a-7b269e33fe62)

![image](https://github.com/user-attachments/assets/f5f19ef4-7e8b-4c06-b96e-7bc9655e7d2f)

**Comment by sqagithub** [comment]
The issue was with my orgUrl. I included the project in the url as follows: https://dev.azure.com/{organization}/{project}
This might help someone. Once I removed the project from the URL, the error went away but my test cases are not updated. This is my test:
![image](https://github.com/user-attachments/assets/26cc7dcf-f7d9-4e6e-b393-4b6c8ac65769)

Any insights?

**Comment by alexneo2003** [comment]
> Any insights?
> 
> 

You define `testCaseIdMatcher` for reporter, but you shouldn't do it if you use default syntax like `[5424]`

**Comment by sqagithub** [comment]
Thanks, that was the issue. It works.
