### ISSUE TITLE
Try to upload using RegEx upload file is not occurring

### ISSUE THREAD

**Issue by mateusvg** [alexneo2003/playwright-azure-reporter#85]
I´m creating a custom report and try to upload to Devops using e RegEx in key attachmentsType.
Also when try to upload a HTML in "test-results" folder the upload of attachment to DevOps of a HTML file is not occurring. Only screenshot, trace and video.

**RegEx tried:** 
/.*\.html$/
/index\.html$/

![image](https://github.com/user-attachments/assets/5b2fe679-5e4b-4f84-ac55-f705879a0e80)

reporter: [
    ['list'],
    ['junit', { outputFile: 'playwright-report-junit/e2e-junit-results.xml' }],
    ['html', { outputFolder: 'playwright-report' }],
    [
      '@alex_neo/playwright-azure-reporter',
      {
        orgUrl: 'XXXX',
        token: 'XXXX,
        planId: 93904,
        projectName: 'XXXX',
        environment: 'QA',
        logging: true,
        testRunTitle: 'Playwright Test Run',
        publishTestResultsMode: 'testRun',
        uploadAttachments: true,
        attachmentsType: ['video', 'screenshot', /index\.html$/,],
        testRunConfig: {

**Comment by alexneo2003** [comment]
Current reporter may upload only attachments that are situated at testInfo.attachments
Please, read documentation
https://playwright.dev/docs/api/class-testresult#test-result-attachments

**Comment by mateusvg** [comment]
Yes but my report is attached in folder attachments:
Also change my RegEx to this:
attachmentsType: ['video', 'screenshot', '^attachments/.*\\.html$', 'html'],
![image](https://github.com/user-attachments/assets/edcf684e-a8df-4384-ab12-514f3d15fcf6)

**Comment by alexneo2003** [comment]
Would you try like `/.+/` - which match with all list of attachments?
if that doesn't work either, you need to check the array of attachments contained in testInfo.attachments. Maybe it doesn't contained what you want

**Comment by mateusvg** [comment]
This worked for me, it saved all files in devops! 
Can you consider put this on documentation? It might help other folks like me!
Thanks a lot!
